### ISSUE TITLE
22個以上のモデルを読み込もうとするとおかしくなる

### ISSUE THREAD

**Issue by AI-Avalon** [p2-3r/Discord-ReadTextBot-for-Style-Bert-VITS2-API#13]
モデル部分に22個以上のモデルがあるとバグります。
0-21 個のモデルまでは表示されてますが、その後ろのモデルが表示されません。
0-21 個のモデルも 0-16 まではちゃんと表示されているのですが、 17 からまた 0と同じモデルが表示されてしまっています。
API側ではちゃんと22個以上のモデルでも認識していました。
これはこちら側の問題でしょうか？

**Comment by AI-Avalon** [comment]
モデルを精査していたら、 id2spk の値が間違っていることに気づきました。
ご迷惑をおかけしました。
ちなみにですが、26個以上のモデルを読み込めるようにする予定はありますか？

**Comment by p2-3r** [comment]
すぐにとは考えてないですが、読み込めるようにはしようかなと思います
(あまり期待しないでください)

**Comment by AI-Avalon** [comment]
ほんとですか！！
ありがとうございます。
お騒がせしました。
